// Minimal hand-written rvtest_config.h for a bare RV32GC + M/S/U + Sv32 DUT.
// Normally generated by ACT4's UDB pass into work/<config>/rvtest_config.h.
// The *_SUPPORTED names mirror the UDB "supported" booleans; get these wrong and
// tests either fail to assemble (#error no CSR known for testing) or self-check
// against the wrong expectations.
#ifndef _RVTEST_CONFIG_H
#define _RVTEST_CONFIG_H

#define UDB_MXLEN 32
#define UDB_ELEN 32
#define UDB_VLEN 0
#define UDB_SEW_MIN 0
#define UDB_TIME_CSR_IMPLEMENTED 1   // drop this to exercise RVTEST_EMULATE_TIME_CSR

// ---- Privilege modes ----
#define M_SUPPORTED
#define S_SUPPORTED
#define U_SUPPORTED
#define STANDARD_SM_SUPPORTED        // enables the framework's trap-handler machinery

// ---- Unprivileged extensions ----
// #define F_SUPPORTED   （待 FPU 里程碑）
// #define D_SUPPORTED   （待 FPU 里程碑）
#define ZCA_SUPPORTED
#define ZAAMO_SUPPORTED
#define ZALRSC_SUPPORTED
#define ZICNTR_SUPPORTED
#define ZIFENCEI_SUPPORTED
// #define ZCD_SUPPORTED             // add whichever ones your UDB header emits
// #define ZCB_SUPPORTED
// #define ZICOND_SUPPORTED
// #define ZAAMO_SUPPORTED
// #define ZALRSC_SUPPORTED

// ---- Privileged extensions ----
// #define SV32_SUPPORTED   （待 MMU 里程碑）
// #define SVINVAL_SUPPORTED / SVADE_SUPPORTED / SVADU_SUPPORTED / SVNAPOT_SUPPORTED / SVPBMT_SUPPORTED
// #define SSTC_SUPPORTED / SSCOFPMF_SUPPORTED / SMSTATEEN_SUPPORTED / SMDBLTRP_SUPPORTED
// #define MSECCFG_SUPPORTED

// ---- PMP（阶段 2A：16 项，G=0 → 4 字节粒度，TOR/NA4/NAPOT 全部实现）----
// 注意三点（依据 riscv-arch-test 框架与 ISA 手册，勿凭直觉改）：
//  · 项数：check_defines.h 要求 UDB_NUM_USABLE_PMP_ENTRIES >= 8，否则 #error；
//    框架给 U/S 铺背景区用 **第 UDB_NUM_USABLE_PMP_ENTRIES-1 项**（rvtest_pmp_macros.h），
//    故必须与实际实现的 16 项一致（背景项落在 PMP15）。
//  · UDB_NUM_PMP_ENTIRES 是上游的**拼写错**，但框架同时引用两者，两个都要定义。
//  · 粒度：**UDB 语义是"log2(字节数)"= G+2**（Spike 参考配置 PMP_GRANULARITY=2 ↔ grain=4 B
//    ↔ 规格 G=0，见 riscv-arch-test/config/spike/spike-rv32-max/*.yaml）。本核 G=0（pmpaddr
//    32 位全可写、NA4 可选），故写 2；写 4（=G=2）会让 PMPSm 的 grain 用例按"低位只读零"判，
//    而 DUT 行为是 G=0 → 签名不符的假失败。
#define UDB_NUM_PMP_ENTRIES 16
#define UDB_NUM_PMP_ENTIRES 16
#define UDB_NUM_USABLE_PMP_ENTRIES 16
#define UDB_PMP_GRANULARITY 2
#define UDB_PMP_NAPOT_SUPPORTED
#define UDB_PMP_TOR_SUPPORTED

// mtvec/stvec alignment: these are BYTE alignment values (powers of two), not
// the power-of-2 exponent used in sail.json's base_alignment field.
#define UDB_MTVEC_MODES_0 1
#define UDB_MTVEC_MODES_1 1
#define UDB_MTVEC_BASE_ALIGNMENT_DIRECT 4
#define UDB_MTVEC_BASE_ALIGNMENT_VECTORED 64
#define UDB_STVEC_BASE_ALIGNMENT_VECTORED 4

#endif // _RVTEST_CONFIG_H
